# Made by Chief-Github 
# https://github.com/Chief-Github

foreground              #EAEAEA
background #14365E
selection_foreground    #1C252C
selection_background    #88BBD6  

cursor_shape block
cursor_trail 20
dynamic_background_opacity yes

background_opacity 0.4

background_blur 100
allow_remote_control yes