# Made by Chief-Github 
# https://github.com/Chief-Github

foreground              #FCEFD2   
background              #FFE9B3
selection_foreground    #1A1110
selection_background    #FFD369   


cursor_shape block
cursor_trail 20
dynamic_background_opacity yes
background_opacity 0.1
background_blur 100
allow_remote_control yes